services:
  drupol\psrcas\CasInterface: '@cas'

  cas.userprovider:
    class: drupol\CasBundle\Security\Core\User\CasUserProvider

  cas.psrhttpfactory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
    arguments:
      $serverRequestFactory: '@nyholm.psr7.psr17_factory'
      $streamFactory: '@nyholm.psr7.psr17_factory'
      $uploadedFileFactory: '@nyholm.psr7.psr17_factory'
      $responseFactory: '@nyholm.psr7.psr17_factory'

  cas.httpfoundationfactory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@cas.psrhttpfactory'
  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@cas.httpfoundationfactory'

  cas.guardauthenticator:
    class: drupol\CasBundle\Security\CasGuardAuthenticator
    arguments:
      $cas: '@cas'
      $uriFactory: '@nyholm.psr7.psr17_factory'
      $httpFoundationFactory: '@cas.httpfoundationfactory'
      $router: '@router'

  cas.request:
    class: Symfony\Component\HttpFoundation\RequestStack
    factory: [ '@request_stack', getCurrentRequest]

  cas.psrrequest:
    class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
    factory: [ '@cas.psrhttpfactory', createRequest ]
    arguments: [ '@cas.request']

  drupol\CasBundle\Controller\:
    resource: '../../src/Controller'
    tags: ['controller.service_arguments']

